// Task 2/React/Student Information Dashboard/src/components/StudentForm.jsx
import { useEffect, useState } from "react";

function StudentForm({ addStudent, editStudent }) {
  const [formData, setFormData] = useState({
    name: "",
    age: "",
    course: "",
    address: "",
  });

  const [error, setError] = useState("");

  useEffect(() => {
    if (editStudent) {
      setFormData(editStudent);
    }
  }, [editStudent]);

  const handleChange = (e) => {
    setFormData({
      ...formData,
      [e.target.name]: e.target.value,
    });
  };

  const handleSubmit = (e) => {
    e.preventDefault();

    // AGE VALIDATION
    if (Number(formData.age) < 0) {
      setError("Age cannot be negative");
      return;
    }

    setError("");

    addStudent(formData);

    setFormData({
      name: "",
      age: "",
      course: "",
      address: "",
    });
  };

  return (
    <form className="student-form" onSubmit={handleSubmit}>
      <input
        type="text"
        name="name"
        placeholder="Enter Name"
        value={formData.name}
        onChange={handleChange}
        required
      />

      <input
        type="number"
        name="age"
        placeholder="Enter Age"
        value={formData.age}
        onChange={handleChange}
        required
      />

      <input
        type="text"
        name="course"
        placeholder="Enter Course"
        value={formData.course}
        onChange={handleChange}
        required
      />

      <input
        type="text"
        name="address"
        placeholder="Enter Address"
        value={formData.address}
        onChange={handleChange}
        required
      />

      {error && <p className="error">{error}</p>}

      <button type="submit">
        {editStudent ? "Update Student" : "Add Student"}
      </button>
    </form>
  );
}

export default StudentForm;

// Task 2/Vue/Student Information Dashboard/src/components/StudentForm.vue
<template>
  <form class="student-form">

    <input
      type="text"
      placeholder="Enter Name"
      v-model="student.name"
    />

    <input
      type="number"
      placeholder="Enter Age"
      v-model="student.age"
    />

    <input
      type="text"
      placeholder="Enter Course"
      v-model="student.course"
    />

    <input
      type="text"
      placeholder="Enter Address"
      v-model="student.address"
    />

    <p class="error" v-if="error">
      {{ error }}
    </p>

    <button type="button" @click="submitForm">
      {{ editStudent ? 'Update Student' : 'Add Student' }}
    </button>

  </form>
</template>

<script>
export default {

  props: ['editStudent'],

  data() {
    return {
      student: {
        name: '',
        age: '',
        course: '',
        address: ''
      },

      error: ''
    };
  },

  watch: {
    editStudent: {
      immediate: true,

      handler(newValue) {
        if (newValue) {
          this.student = { ...newValue };
        }
      }
    }
  },

  methods: {

    submitForm() {

      if (Number(this.student.age) < 0) {
        this.error = 'Age cannot be negative';
        return;
      }

      this.error = '';

      this.$emit('student-added', {
        ...this.student
      });

      this.student = {
        name: '',
        age: '',
        course: '',
        address: ''
      };
    }
  }
};
</script>

<style scoped>
.student-form {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.student-form input {
  padding: 12px;
  border: 1px solid #ccc;
  border-radius: 6px;
}

.student-form button {
  padding: 12px;
  background: black;
  color: white;
  border: none;
  border-radius: 6px;
  cursor: pointer;
}

.error {
  color: red;
}
</style>
